name: Post-Template Initialization
on:
  push:
    branches: ["**"]

jobs:
  setup:
    if: github.run_number == 1 && github.repository != 'FriquetLuca/vite_rustify'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v7
      
      - name: Replace placeholders
        run: |
          export CURRENT_YEAR=$(date +'%Y')
          export CURRENT_DATE=$(date +'%Y-%m-%d')
          export NAME="${{ github.event.repository.name }}"
          export OWNER="${{ github.repository_owner }}"
          export DESC="${{ github.event.repository.description }}"
          URL="https://${OWNER}.github.io/${NAME}/"
          export PRETTY_NAME=$(python3 -c "import os; print(os.environ['NAME'].replace('-', ' ').replace('_', ' ').title())")
          export CLEAN_DESC=$(python3 -c "import os; d = os.environ.get('DESC', ''); print(d if d and d != 'None' else 'A Rust/Typescript project template.')")

          sed -i "s/TEMPLATE_NAME/${NAME}/g" README.md fastify_vite_ssr/package.json vite_csr/package.json fastify_vite_ssr/package-lock.json vite_csr/package-lock.json
          sed -i "s/TEMPLATE_OWNER/${OWNER}/g" README.md fastify_vite_ssr/package.json vite_csr/package.json fastify_vite_ssr/package-lock.json vite_csr/package-lock.json LICENSE
          sed -i "s|TEMPLATE_DESCRIPTION|$CLEAN_DESC|g" README.md
          sed -i "s|TEMPLATE_URL|${URL}|g" README.md
          sed -i "s/TEMPLATE_PRETTY_NAME/$PRETTY_NAME/g" README.md fastify_vite_ssr/index.html vite_csr/index.html
          sed -i "s|CURRENT_DATE|$CURRENT_DATE|g" fastify_vite_ssr/CHANGELOG.md vite_csr/CHANGELOG.md
          sed -i "s|CURRENT_YEAR|$CURRENT_YEAR|g" LICENSE
          
      - name: Cleanup and Commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          rm .github/workflows/post-init.yml
          git add .
          # Check if there are changes before committing to avoid errors
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: initialize project" && git push)